src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @Vich\Uploadable
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     */
    private $user;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="post_image", fileNameProperty="imageName")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
}

templates/components/post.html.twig
<div class="card my-1 border w-50" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ post.name }}</h5>
    <p class="card-text">{{ post.content }}</p>
    {% if post.imageName is not null %}
      <img src="{{ vich_uploader_asset(post) | imagine_filter('my_thumb') }}" alt="{{ post.name }}">
    {% endif %}
    <p>{{ post.user.firstName }}  {{ post.user.lastName }}</p>
  </div>
</div>

templates/components/userCard.html.twig
<div class="card my-1 border" style="width: 18rem;">
  <div class="card-body container">
    <div class="row">
      <div class="col">
        <h5 class="card-title row px-2">{{ user.firstName }}</h5>
        <h4 class="card-title row px-2">{{ user.lastName }}</h4>
        <p class="m-0">{{ user.createdAt|date('d/m/Y') }}</p>
      </div>
      <div class="col align-items-center justify-content-center">
        {% if user.imageName is not null %}
        <div class="d-flex align-items-center justify-content-center">
          <img class="w-75 h-75" src="{{ vich_uploader_asset(user) | imagine_filter('my_thumb') }}" alt="{{ user.firstName }}">
        </div>
        {% else %}
        <div class="d-flex align-items-center justify-content-center">
          <img class="w-75 h-75 opacity-50" src="social/user_placeholder.svg">
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>